#ifndef GUARD_HEARTGOLD_SPEEDCHOICE_CONSTANTS_SPEEDCHOICE_H
#define GUARD_HEARTGOLD_SPEEDCHOICE_CONSTANTS_SPEEDCHOICE_H

#define SPEEDCHOICE_HOLD_TO_MASH     0
#define SPEEDCHOICE_SPINNERS         1
#define SPEEDCHOICE_ROCKETLESS       2
#define SPEEDCHOICE_HEALTH_BARS      3
#define SPEEDCHOICE_BETTER_MARTS     4
#define SPEEDCHOICE_GOOD_EARLY_WILDS 5
#define SPEEDCHOICE_BIKE_MUSIC       6
#define SPEEDCHOICE_SURF_MUSIC       7
#define SPEEDCHOICE_EVIL_HAU         8
#define SPEEDCHOICE_FRIENDLESS       9
#define SPEEDCHOICE_KIMONO_SEGMENTS  10
#define SPEEDCHOICE_DEX_BEEPS        11
#define SPEEDCHOICE_HMS              12
#define SPEEDCHOICE_EXP              13
#define SPEEDCHOICE_EARLY_KANTO      14
#define SPEEDCHOICE_TRAINER_VISION   15
#define SPEEDCHOICE_GOAL             16
#define SPEEDCHOICE_SETTINGS_MAX     17

#define SPEEDCHOICE_HOLD_TO_MASH_NO  0
#define SPEEDCHOICE_HOLD_TO_MASH_YES 1

#define SPEEDCHOICE_SPINNERS_PURGE 0
#define SPEEDCHOICE_SPINNERS_KEEP  1
#define SPEEDCHOICE_SPINNERS_HELL  2
#define SPEEDCHOICE_SPINNERS_WHY   3

#define SPEEDCHOICE_ROCKETLESS_KEEP  0
#define SPEEDCHOICE_ROCKETLESS_PURGE 1

#define SPEEDCHOICE_HEALTH_BARS_VANILLA 0
#define SPEEDCHOICE_HEALTH_BARS_FAST    1
#define SPEEDCHOICE_HEALTH_BARS_INSTANT 2

#define SPEEDCHOICE_BETTER_MARTS_OFF 0
#define SPEEDCHOICE_BETTER_MARTS_ON  1

#define SPEEDCHOICE_GOOD_EARLY_WILDS_OFF 0
#define SPEEDCHOICE_GOOD_EARLY_WILDS_ON  1

#define SPEEDCHOICE_BIKE_MUSIC_OFF 0
#define SPEEDCHOICE_BIKE_MUSIC_ON  1

#define SPEEDCHOICE_SURF_MUSIC_OFF 0
#define SPEEDCHOICE_SURF_MUSIC_ON  1

#define SPEEDCHOICE_EVIL_HAU_OFF 0
#define SPEEDCHOICE_EVIL_HAU_ON  1

#define SPEEDCHOICE_FRIENDLESS_OFF 0
#define SPEEDCHOICE_FRIENDLESS_ON  1

#define SPEEDCHOICE_KIMONO_SEGMENTS_KEEP  0
#define SPEEDCHOICE_KIMONO_SEGMENTS_PURGE 1

#define SPEEDCHOICE_DEX_BEEPS_OFF 0
#define SPEEDCHOICE_DEX_BEEPS_ON  1

#define SPEEDCHOICE_HMS_NORMAL 0
#define SPEEDCHOICE_HMS_NERF   1
#define SPEEDCHOICE_HMS_RANDOM 2

#define SPEEDCHOICE_EXP_NORMAL 0
#define SPEEDCHOICE_EXP_BW     1
#define SPEEDCHOICE_EXP_NONE   2

#define SPEEDCHOICE_EARLY_KANTO_OFF 0
#define SPEEDCHOICE_EARLY_KANTO_ON  1

#define SPEEDCHOICE_TRAINER_VISION_NORMAL 0
#define SPEEDCHOICE_TRAINER_VISION_MAX    1

#define SPEEDCHOICE_GOAL_LANCE  0
#define SPEEDCHOCIE_GOAL_RED    1
#define SPEEDCHOICE_GOAL_MANUAL 2

#endif // GUARD_HEARTGOLD_SPEEDCHOICE_CONSTANTS_SPEEDCHOICE_H
