#ifndef GUARD_HEARTGOLD_SPEEDCHOICE_CONSTANTS_SPEEDCHOICE_H
#define GUARD_HEARTGOLD_SPEEDCHOICE_CONSTANTS_SPEEDCHOICE_H

#define SPEEDCHOICE_HOLD_TO_MASH     0
#define SPEEDCHOICE_SPINNERS         1
#define SPEEDCHOICE_ROCKETLESS       2
#define SPEEDCHOICE_HEALTH_BARS      3
#define SPEEDCHOICE_BETTER_MARTS     4
#define SPEEDCHOICE_GOOD_EARLY_WILDS 5
#define SPEEDCHOICE_BIKE_MUSIC       6
#define SPEEDCHOICE_SURF_MUSIC       7
#define SPEEDCHOICE_EVIL_HAU         8

#endif // GUARD_HEARTGOLD_SPEEDCHOICE_CONSTANTS_SPEEDCHOICE_H
